module.exports = {
    plugins: ["jest"],
    extends: [
        "airbnb-base",
        "plugin:import/errors",
        "plugin:import/warnings",
        "plugin:jest/recommended",
    ],
    rules: {
        "no-console": "off",
        "no-use-before-define": 0,
        "no-shadow": "off",
        "no-unused-vars": "off",
        "no-undef": "off",
        "no-empty-function": "off",
        "no-useless-constructor": "off",
        "no-plusplus": "off",
        "max-classes-per-file": "off",
        "class-methods-use-this": "off",
        "consistent-return": "off",
        "lines-between-class-members": "off",
        "no-underscore-dangle": "off",
        "prefer-destructuring": "off",
        "no-unneeded-ternary": "off",
        "new-cap": "off",
        "ban-ts-comment": "off",
        "no-param-reassign": "off",
        "no-return-await": "off",
        "no-restricted-syntax": "off",
        "guard-for-in": "off",
        "no-await-in-loop": "off",
        "import/extensions": 0,
        "import/no-unresolved": 0,
        "import/prefer-default-export": "off",
        "import/no-extraneous-dependencies": "off",
        "jest/no-deprecated-functions": "off",
    },
};
